version: "3.9"

services:
    app:
        build: .
        command: /app/node_modules/.bin/live-server /app/docs
        ports:
            - "8080:8080"
        volumes:
            - ./docs:/app/docs
